type: standard

lang: g++

limits:
  time: 2
  real_time: 2
  memory: 10000

  stack: 10000 #optionally

groups:
  - id: 0
    range: [1, 1]
    cost: 30
    depends: []
  - id: 1
    range: [2, 2]
    cost: 70
    depends: [0]
